#Ubuntu
FROM ubuntu:latest

RUN apt update && apt install -y build-essential git nano vim make
RUN sudo apt-get install gcc lcov gcovr 
RUN sudo apt-get install doxygen graphviz 
RUN pip install pre-commit  

ENTRYPOINT ["tail", "-f", "/dev/null"]

CMD [ "/bin/bash" ]
