name: Generate Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Doxygen
      run: sudo apt-get install doxygen graphviz
    - name: Generate documentation
      run: cd code/ && make test docs
